import { raw } from 'hono/html'
import type { FC, JSX, PropsWithChildren } from 'hono/jsx'

import { styleObjectFromUnknown } from '../style'

type ElementProps<Tag extends keyof JSX.IntrinsicElements> = JSX.IntrinsicElements[Tag]
type SpaceValue = number | string
type FlexDirection = 'column' | 'row'
type FlexAlign = 'baseline' | 'bottom' | 'center' | 'middle' | 'stretch' | 'top'
type FlexJustify = 'center' | 'end' | 'left' | 'right' | 'space-between' | 'start'
type BoxElement = 'div' | 'span' | 'table' | 'tbody' | 'tr' | 'td'

const PRESENTATION_TABLE_PROPS = {
  border: 0,
  cellPadding: '0',
  cellSpacing: '0',
  role: 'presentation',
} as const

type BoxProps<As extends BoxElement = 'div'> = PropsWithChildren<
  Omit<ElementProps<As>, 'children'> & {
    as?: As
  }
>

type SpacerProps = Omit<ElementProps<'div'>, 'children'> & {
  height?: SpaceValue
  width?: SpaceValue
}

type FlexProps = PropsWithChildren<
  Omit<ElementProps<'table'>, 'children'> & {
    align?: FlexAlign
    direction?: FlexDirection
    gap?: SpaceValue
    justify?: FlexJustify
  }
>

type GridProps = PropsWithChildren<
  Omit<ElementProps<'table'>, 'children'> & {
    align?: FlexAlign
    columns?: number
    gap?: SpaceValue
  }
>

type CardProps = PropsWithChildren<
  Omit<ElementProps<'table'>, 'children' | 'width'> & {
    backgroundColor?: string
    borderColor?: string
    borderWidth?: SpaceValue
    contentStyle?: JSX.CSSProperties
    padding?: SpaceValue
    width?: SpaceValue
  }
>

const toCssSpace = (value: SpaceValue | undefined): string | undefined => {
  if (typeof value === 'number') {
    return `${value}px`
  }

  const trimmed = value?.trim()
  return trimmed === '' ? undefined : trimmed
}

const getTableAlign = (
  justify: FlexJustify | undefined,
): 'center' | 'left' | 'right' | undefined => {
  if (justify === 'center') {
    return 'center'
  }

  if (justify === 'end' || justify === 'right') {
    return 'right'
  }

  if (justify === 'left' || justify === 'start') {
    return 'left'
  }

  return undefined
}

const getCellVAlign = (
  align: FlexAlign | undefined,
): 'baseline' | 'bottom' | 'middle' | 'top' | undefined => {
  if (align === 'center' || align === 'middle') {
    return 'middle'
  }

  if (align === 'bottom') {
    return 'bottom'
  }

  if (align === 'baseline') {
    return 'baseline'
  }

  return align === 'stretch' ? undefined : 'top'
}

const renderSpacerCell = (gap: string | undefined, direction: FlexDirection, index: number) => {
  if (!gap || index === 0) {
    return null
  }

  if (direction === 'column') {
    return (
      <tr aria-hidden="true">
        <td height={gap} style={{ fontSize: '0px', lineHeight: '0px' }}>
          &nbsp;
        </td>
      </tr>
    )
  }

  return <td aria-hidden="true" style={{ fontSize: '0px', lineHeight: '0px' }} width={gap} />
}

const chunkChildren = (children: unknown[], columns: number): unknown[][] => {
  const rows: unknown[][] = []
  for (let index = 0; index < children.length; index += columns) {
    rows.push(children.slice(index, index + columns))
  }
  return rows
}

/**
 * Root `<html>` element for an email document.
 *
 * @param props - Standard `<html>` attributes and children.
 * @returns The root email document element.
 *
 * @example
 * ```tsx
 * <Html lang="en">
 *   <Head />
 *   <Body>Hello</Body>
 * </Html>
 * ```
 */
export const Html: FC<PropsWithChildren<ElementProps<'html'>>> = ({ lang = 'en', ...props }) => (
  <html lang={lang} {...props} />
)

/**
 * Email document head. Head styles generated by other helpers are normalized into this element.
 *
 * @param props - Standard `<head>` attributes.
 * @returns A head element.
 *
 * @example
 * ```tsx
 * <Html>
 *   <Head>
 *     <title>Welcome</title>
 *   </Head>
 * </Html>
 * ```
 */
export const Head: FC<PropsWithChildren<ElementProps<'head'>>> = ({ children, ...props }) => (
  <head {...props}>
    {raw('<meta charset="utf-8">')}
    {children}
  </head>
)

/**
 * Email document body.
 *
 * @param props - Standard `<body>` attributes and children.
 * @returns The email document body.
 *
 * @example
 * ```tsx
 * <Body style={{ backgroundColor: '#f6f9fc' }}>
 *   <Text>Hello</Text>
 * </Body>
 * ```
 */
export const Body: FC<PropsWithChildren<ElementProps<'body'>>> = (props) => <body {...props} />

/**
 * Generic email-safe wrapper that can render as a limited set of common elements.
 *
 * @param props - Wrapper props.
 * @param props.as - Element tag to render. Defaults to `div`.
 * @returns The selected wrapper element.
 *
 * @example
 * ```tsx
 * <Box as="td" style={{ padding: '16px' }}>
 *   <Text>Content</Text>
 * </Box>
 * ```
 */
export const Box = <As extends BoxElement = 'div'>({ as, style, ...props }: BoxProps<As>) => {
  const Tag = as ?? 'div'
  return <Tag {...props} style={styleObjectFromUnknown(style)} />
}

/**
 * Explicit spacing block for email clients.
 *
 * @param props - Spacer props.
 * @param props.height - Spacer height. Numbers are converted to pixels.
 * @param props.width - Spacer width. Numbers are converted to pixels.
 * @returns A hidden spacing `<div>`.
 *
 * @example
 * ```tsx
 * <Text>First paragraph</Text>
 * <Spacer height={24} />
 * <Text>Second paragraph</Text>
 * ```
 */
export const Spacer: FC<SpacerProps> = ({ height = 16, style, width = '100%', ...props }) => (
  <div
    {...props}
    aria-hidden="true"
    style={{
      fontSize: '0px',
      lineHeight: '0px',
      height: toCssSpace(height),
      width: toCssSpace(width),
      ...styleObjectFromUnknown(style),
    }}
  >
    &nbsp;
  </div>
)

/**
 * Table-based flex-like layout for email clients.
 *
 * @param props - Flex layout props.
 * @param props.align - Vertical alignment for child cells. Defaults to `top`.
 * @param props.direction - Row or column layout. Defaults to `row`.
 * @param props.gap - Space between children. Numbers are converted to pixels.
 * @param props.justify - Horizontal table alignment or `space-between`.
 * @returns A presentation table that lays out its children.
 *
 * @example
 * ```tsx
 * <Flex align="middle" gap={12} justify="center">
 *   <Text>Left</Text>
 *   <Text>Right</Text>
 * </Flex>
 * ```
 */
export const Flex: FC<FlexProps> = ({
  align = 'top',
  children,
  direction = 'row',
  gap,
  justify,
  style,
  ...props
}) => {
  const childArray = Array.isArray(children) ? children : [children]
  const gapSpace = toCssSpace(gap)
  const valign = getCellVAlign(align)
  const tableAlign = getTableAlign(justify)
  const tableStyle = {
    ...styleObjectFromUnknown(style),
    ...(justify === 'space-between' ? { width: '100%' } : {}),
  }

  if (direction === 'column') {
    return (
      <table {...PRESENTATION_TABLE_PROPS} {...props} align={tableAlign} style={tableStyle}>
        <tbody>
          {childArray.map((child, index) => (
            <>
              {renderSpacerCell(gapSpace, direction, index)}
              <tr>
                <td valign={valign}>{child}</td>
              </tr>
            </>
          ))}
        </tbody>
      </table>
    )
  }

  return (
    <table {...PRESENTATION_TABLE_PROPS} {...props} align={tableAlign} style={tableStyle}>
      <tbody>
        <tr>
          {childArray.map((child, index) => (
            <>
              {renderSpacerCell(gapSpace, direction, index)}
              <td
                style={justify === 'space-between' ? { width: `${100 / childArray.length}%` } : {}}
                valign={valign}
              >
                {child}
              </td>
            </>
          ))}
        </tr>
      </tbody>
    </table>
  )
}

/**
 * Table-based grid layout with a fixed number of columns.
 *
 * @param props - Grid layout props.
 * @param props.align - Vertical alignment for child cells. Defaults to `top`.
 * @param props.columns - Number of columns per row. Defaults to `2`.
 * @param props.gap - Space between grid cells. Numbers are converted to pixels.
 * @returns A full-width presentation table grid.
 *
 * @example
 * ```tsx
 * <Grid columns={2} gap={16}>
 *   <Card><Text>One</Text></Card>
 *   <Card><Text>Two</Text></Card>
 * </Grid>
 * ```
 */
export const Grid: FC<GridProps> = ({
  align = 'top',
  children,
  columns = 2,
  gap,
  style,
  ...props
}) => {
  const childArray = Array.isArray(children) ? children : [children]
  const columnCount = Math.max(1, Math.floor(columns))
  const gapSpace = toCssSpace(gap)
  const rows = chunkChildren(childArray, columnCount)
  const valign = getCellVAlign(align)
  const cellWidth = `${100 / columnCount}%`

  return (
    <table
      {...PRESENTATION_TABLE_PROPS}
      width="100%"
      {...props}
      style={styleObjectFromUnknown(style)}
    >
      <tbody>
        {rows.map((row, rowIndex) => (
          <>
            {gapSpace && rowIndex > 0 ? (
              <tr aria-hidden="true">
                <td
                  colSpan={columnCount * 2 - 1}
                  height={gapSpace}
                  style={{ fontSize: '0px', lineHeight: '0px' }}
                >
                  &nbsp;
                </td>
              </tr>
            ) : null}
            <tr>
              {row.map((child, columnIndex) => (
                <>
                  {gapSpace && columnIndex > 0 ? (
                    <td
                      aria-hidden="true"
                      style={{ fontSize: '0px', lineHeight: '0px' }}
                      width={gapSpace}
                    />
                  ) : null}
                  <td style={{ width: cellWidth }} valign={valign} width={cellWidth}>
                    {child}
                  </td>
                </>
              ))}
            </tr>
          </>
        ))}
      </tbody>
    </table>
  )
}

/**
 * Bordered table container with email-safe padding and background defaults.
 *
 * @param props - Card props.
 * @param props.backgroundColor - Cell background color.
 * @param props.borderColor - Border color.
 * @param props.borderWidth - Border width. Numbers are converted to pixels.
 * @param props.contentStyle - Inline style applied to the inner content cell.
 * @param props.padding - Cell padding. Numbers are converted to pixels.
 * @param props.width - Table width.
 * @returns A one-cell presentation table.
 *
 * @example
 * ```tsx
 * <Card padding={24} borderColor="#e5e7eb">
 *   <Text>Plan updated.</Text>
 * </Card>
 * ```
 */
export const Card: FC<CardProps> = ({
  backgroundColor = '#ffffff',
  borderColor = '#e5e7eb',
  borderWidth = 1,
  children,
  contentStyle,
  padding = 24,
  style,
  width = '100%',
  ...props
}) => {
  const borderSpace = toCssSpace(borderWidth) ?? '1px'
  const cardWidth = toCssSpace(width)

  return (
    <table
      {...PRESENTATION_TABLE_PROPS}
      width={cardWidth}
      {...props}
      style={styleObjectFromUnknown(style)}
    >
      <tbody>
        <tr>
          <td
            style={{
              backgroundColor,
              border: `${borderSpace} solid ${borderColor}`,
              padding: toCssSpace(padding),
              ...styleObjectFromUnknown(contentStyle),
            }}
          >
            {children}
          </td>
        </tr>
      </tbody>
    </table>
  )
}

/**
 * Full-width presentation table for wrapping email sections.
 *
 * @param props - Standard `<table>` attributes and children.
 * @returns A full-width presentation table.
 *
 * @example
 * ```tsx
 * <Container style={{ maxWidth: '560px', margin: '0 auto' }}>
 *   <Text>Hello</Text>
 * </Container>
 * ```
 */
export const Container: FC<PropsWithChildren<ElementProps<'table'>>> = ({ children, ...props }) => (
  <table {...PRESENTATION_TABLE_PROPS} width="100%" {...props}>
    <tbody>
      <tr>
        <td>{children}</td>
      </tr>
    </tbody>
  </table>
)

/**
 * Full-width presentation table whose direct children are table rows/cells.
 *
 * @param props - Standard `<table>` attributes and children.
 * @returns A section table with one row.
 *
 * @example
 * ```tsx
 * <Section>
 *   <Column width="50%">Left</Column>
 *   <Column width="50%">Right</Column>
 * </Section>
 * ```
 */
export const Section: FC<PropsWithChildren<ElementProps<'table'>>> = ({ children, ...props }) => (
  <table {...PRESENTATION_TABLE_PROPS} width="100%" {...props}>
    <tbody>
      <tr>{children}</tr>
    </tbody>
  </table>
)

/**
 * Table row helper for manual email table layouts.
 *
 * @param props - Standard `<tr>` attributes and children.
 * @returns A table row.
 *
 * @example
 * ```tsx
 * <Row>
 *   <Column>Receipt total</Column>
 *   <Column>$42.00</Column>
 * </Row>
 * ```
 */
export const Row: FC<PropsWithChildren<ElementProps<'tr'>>> = ({ children, ...props }) => (
  <tr {...props}>{children}</tr>
)

/**
 * Table cell helper for manual email table layouts.
 *
 * @param props - Standard `<td>` attributes and children.
 * @returns A table cell.
 *
 * @example
 * ```tsx
 * <Column style={{ padding: '12px' }}>
 *   <Text>Cell content</Text>
 * </Column>
 * ```
 */
export const Column: FC<PropsWithChildren<ElementProps<'td'>>> = ({ children, ...props }) => (
  <td {...props}>{children}</td>
)
